source = $HOME/.cache/wal/colors-hyprland.conf

general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = $HOME/.current_wallpaper
    blur_size = 5
    blur_passes = 4
    noise = 0.0117
    contrast = 1.3
    brightness = 0.8
    vibrancy = 0.21
    vibrancy_darkness = 0.0
}

# Hours
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
    color = $color6
    font_size = 150
    font_family = Geist Mono SemiBold
    position = 0, 180   # Shifted up slightly from center
    halign = center
    valign = center
}

# Minutes
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = $color6
    font_size = 150
    font_family = Geist Mono SemiBold
    position = 0, 30    # Shifted up just a bit to sit under Hours
    halign = center
    valign = center
}

# Day-Month
label {
    monitor =
    text = cmd[update:18000000] echo "<b>$(date +'%A, %d %b')</b>"
    color = $color7
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, -60   # Shifted down to sit under Minutes
    halign = center
    valign = center
}

# Input Field
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(255, 255, 255, 0.1) # Glass effect
    font_color = $color6
    
    fade_on_empty = false
    rounding = -1
    check_color = $color2
    fail_color = $color1
    
    placeholder_text = <i><span font_family="Geist Mono">Unlock...</span></i>
    hide_input = false
    position = 0, -150  # Shifted further down to clear the date
    halign = center
    valign = center
}